### ISSUE TITLE
Unicode piece characters

### ISSUE THREAD

**Issue by heliosdrm** [romstad/Chess.jl#1]
Wouldn't be nice to print the board with the Unicode characters for the corresponding pieces (at least in environments that support Unicode, like Atom, and REPL if not in Windows)?:

- P : &#x2659;
- N : &#x2658;
- B : &#x2657;
- R : &#x2656;
- Q : &#x2655;
- K : &#x2654;
- p : &#x265F;
- n : &#x265E;
- b : &#x265D;
- r : &#x265C;
- q : &#x265B;
- k : &#x265A;

**Comment by romstad** [comment]
Thanks for the suggestion!

I actually had that at some point, but removed it for some reason. I don't remember why; I guess I didn't like the look of it. I'll consider reintroducing it, while making it optional.

There is still an undocumented `tounicode(p::Piece)` function, by the way.

**Comment by romstad** [comment]
I added an optional named parameter `unicode` (default `false`) to `pprint(b::Board)`. It doesn't look good here, but I suppose it depends on your font and environment.
