### ISSUE TITLE
Suppress Printing of Game When Loading from PGN

### ISSUE THREAD

**Issue by prescient** [romstad/Chess.jl#16]
First, thanks for the package. It is awesome and I know writing open source code can be a little thankless. Second, I have a suspicion that I'm doing something wrong here, but is there a way to suppress the printing of the entire game when you return a game from a pgn?

I have functions that look like those below, and when I run the get_game function it prints the entire game. I am a Julia noob so I might be missing something painfully obvious, and if so apologies in advance.

```
function create_game_id(g)
         # creates game IDs based on players, site and date played
	  white_player = Chess.whiteplayer(g)
	  black_player = Chess.blackplayer(g)
	  site         = Chess.site(g)
	  date_played  = Chess.dateplayed(g)
	  game_string  = string(white_player, " - ", black_player, " | ", site, " ", date_played)
	  game_string
end

function get_game(pgn, game_id)
        # searches the pgn file for game IDs
	for g in gamesinfile(pgn, annotations = true)
		if(create_game_id(g) == game_id)
			return g
		end
	end
end

pgn          = "C:\\Users\\<user>\\Desktop\\Chess\\Books\\PGN\\CaroKannMBM.pgn"
game_name    = "Atkins, H. - Capablanca, J. | nothing 1922-01-01"
g = get_game(pgn, game_name)
```

**Comment by fsmosca** [comment]
I tried your code and `get_game()` does not print the entire game.

```julia
function get_game(pgn, game_id)
    # searches the pgn file for game IDs
    println("string to search: $(game_id)")
    for g in gamesinfile(pgn, annotations = true)
        gid = create_game_id(g)
        println("string in pgn: $gid")
        if gid == game_id
            println("found")
            return g
        end
    end
end


pgn          = "games.pgn"
game_name    = "ncsf-2021-04-22_nn48-final - ncsf-2021-04-22_tn48-34 | nothing 2021-05-10"
g = get_game(pgn, game_name)

```

### output
```
string to search: ncsf-2021-04-22_nn48-final - ncsf-2021-04-22_tn48-34 | nothing 2021-05-10
string in pgn: ncsf-2021-04-22_nn48-final - ncsf-2021-04-22_tn48-34 | nothing 2021-05-10
found
```

**Comment by fsmosca** [comment]
For julia repl try to add semicolon.
`g = get_game(pgn, game_name);`

**Comment by prescient** [comment]
";" works thanks!

As an aside is there a better way to access games? Or is something similar to what I've done the best way to pull a game from a PGN?

**Comment by prescient** [comment]
Closing this.

**Comment by romstad** [comment]
Thanks for your kind words, @prescient!

> ";" works thanks!
> 
> As an aside is there a better way to access games? Or is something similar to what I've done the best way to pull a game from a PGN?

Looks pretty good to me.

The printing of return values is pretty standard in Julia when working at the REPL. Most of the time, it's what you want. When it isn't, you just add a semicolon, as @fsmosca explained.
