### ISSUE TITLE
Castling rights not properly updated

### ISSUE THREAD

**Issue by ezlife77** [romstad/Chess.jl#2]
Given position: r1bqkbnr/ppp2pp1/2np4/4p3/6P1/2N1P3/PPPP1PB1/R1BQK1NR b KQkq - 0 6

If black plays Rxh1, the correct fen should be r1bqkbn1/ppp2pp1/2np4/4p3/6P1/2N1P3/PPPP1PB1/R1BQK1Nr w Qq - 0 7, but Chess.jl will give r1bqkbn1/ppp2pp1/2np4/4p3/6P1/2N1P3/PPPP1PB1/R1BQK1Nr w Qkq - thereby listing kingside catling as a legal move for black.

**Comment by dkappe** [comment]
I can confirm this.

const FEN = "r1bqk2r/p4pb1/2pp1np1/6P1/2PPp3/2N5/PP3PB1/R1BQK2R b KQkq -"

board = fromfen(FEN)
mv = movefromstring("h8h1")
ui = domove!(board, mv)
println(fen(board))

Gives “r1bqk3/p4pb1/2pp1np1/6P1/2PPp3/2N5/PP3PB1/R1BQK2r w Qkq -“

**Comment by romstad** [comment]
Fixed now in version 0.4.0, which should be out very soon. Thank you for reporting!

@dkappe : There is no need to do this:
```
mv = movefromstring("h8h1")
ui = domove!(board, mv)
```

The function `domove!` (and similar functions like `domove`, `domoves!`, `addmove`, etc.) understands strings as input. You can do `ui = domove!(board, "h8h1")` or even `ui = domove!(board, "Rxh1+")`.
