### ISSUE TITLE
pickbookmove() potentially broken? 

### ISSUE THREAD

**Issue by slenderq** [romstad/Chess.jl#22]
Hi there, noticed that the `pickbookmove()` function broke in my code after this commit:
https://github.com/romstad/Chess.jl/commit/529b11ba117706bc00fe1bf59261b05aff36069c
(I noticed this issue after updating the package)

My exact call is:
```move = pickbookmove(board, "my-book.obk")```
and the error I now get is
``ERROR: LoadError: MethodError: no method matching pickbookmove(::Board, ::String)
Closest candidates are:
  pickbookmove(::Board; bookfile, minscore, mingamecount) at /home/vscode/.julia/packages/Chess/86E71/src/book.jl:665``

Did something change about how this function is called? I can't seem to find any working examples/documentation on if the way to use this function has changed.

Thanks!

**Comment by romstad** [comment]
Hello, 

Sorry about not responding earlier to this one. The book name is now a named parameter. You'll have to do `pickbookmove(board, bookfile="my-book.obk")` instead. 

Obviously this is a breaking change and should have been reflected in the library version number. My mistake.

**Comment by slenderq** [comment]
Ah no worries, thanks for the fix!
