### ISSUE TITLE
No threefold repetion draw

### ISSUE THREAD

**Issue by dave7895** [romstad/Chess.jl#33]
Is it on purpose that the `isdraw(g::Game)` doesn't look if it's a draw by threefold repetition, but only for material and fifty move rule?

**Comment by romstad** [comment]
I'm not sure I understand the question correctly, but it does check for repetition draws. The function definition looks like this:

```julia
function isdraw(g::SimpleGame)::Bool
    isdraw(board(g)) || isrepetitiondraw(g)
end
```

The `isrepetitiondraw(g)` part checks for a draw by repetition

**Comment by dave7895** [comment]
That's good, but somewhat strange as I don't know exactly how I came to think that it doesn't check, but am pretty sure that I looked into the code.
