### ISSUE TITLE
InexactError: trunc(UInt8, 256) for long, random games

### ISSUE THREAD

**Issue by fonsp** [romstad/Chess.jl#9]
I keep re-running the cell, sometimes I get a completed game, sometimes an error. It looks like `moves` returned an invalid move.

https://user-images.githubusercontent.com/6933510/114249719-adcff600-999b-11eb-92a0-9c1e26f67287.mov

**Comment by romstad** [comment]
This one was already fixed in master some time ago. I guess I should push a new release soon.
